version: "3.9"

services:
  jenkin-slave:
    image: jenkin-slave:latest
    ports:
      - 2222:22
    volumes:
      - /var/jenkins_home_slave:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock