version: "3.9"

services:
  jenkin:
    image: jenkinlab:latest
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkin_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkin_home:
